name: _error
timestamp: 1447928879
preset:
  image: 'gantry-admin://images/layouts/error.png'
  name: _error
  timestamp: 1446482325
positions:
  drawer: Drawer
  top-a: Top-a
  top-b: Top-b
  top-c: Top-c
  top-d: Top-d
  navigation-a: Navigation-a
  navigation-b: Navigation-b
  navigation-c: Navigation-c
  navigation-d: Navigation-d
  breadcrumb-a: Breadcrumb-a
  breadcrumb-b: Breadcrumb-b
  breadcrumb-c: Breadcrumb-c
  breadcrumb-d: Breadcrumb-d
  fullwidth: Fullwidth
  showcase-a: Showcase-a
  showcase-b: Showcase-b
  showcase-c: Showcase-c
  showcase-d: Showcase-d
  intro-a: Intro-a
  intro-b: Intro-b
  intro-c: Intro-c
  intro-d: Intro-d
  feature-a: Feature-a
  feature-b: Feature-b
  feature-c: Feature-c
  feature-d: Feature-d
  subfeature-a: Subfeature-a
  subfeature-b: Subfeature-b
  subfeature-c: Subfeature-c
  subfeature-d: Subfeature-d
  utility-a: Utility-a
  utility-b: Utility-b
  utility-c: Utility-c
  utility-d: Utility-d
  maintop-a: Maintop-a
  maintop-b: Maintop-b
  maintop-c: Maintop-c
  maintop-d: Maintop-d
  sidebar-left: Sidebar-left
  content-top-a: Content-top-a
  content-top-b: Content-top-b
  content-bottom-a: Content-bottom-a
  content-bottom-b: Content-bottom-b
  sidebar-right: Sidebar-right
  mainbottom-a: Mainbottom-a
  mainbottom-b: Mainbottom-b
  mainbottom-c: Mainbottom-c
  mainbottom-d: Mainbottom-d
  extension-a: Extension-a
  extension-b: Extension-b
  extension-c: Extension-c
  extension-d: Extension-d
  additional-a: Additional-a
  additional-b: Additional-b
  additional-c: Additional-c
  additional-d: Additional-d
  prebottom-a: Prebottom-a
  prebottom-b: Prebottom-b
  prebottom-c: Prebottom-c
  prebottom-d: Prebottom-d
  bottom-a: Bottom-a
  bottom-b: Bottom-b
  bottom-c: Bottom-c
  bottom-d: Bottom-d
  afterbottom-a: Afterbottom-a
  afterbottom-b: Afterbottom-b
  afterbottom-c: Afterbottom-c
  afterbottom-d: Afterbottom-d
  last-a: Last-a
  last-b: Last-b
  last-c: Last-c
  last-d: Last-d
  footer-a: Footer-a
  footer-b: Footer-b
  footer-c: Footer-c
  footer-d: Footer-d
  copyright-a: Copyright-a
  copyright-b: Copyright-b
  copyright-c: Copyright-c
  copyright-d: Copyright-d
  offcanvas-a: Offcanvas-a
  offcanvas-b: Offcanvas-b
